name: Deploy

on:
  push:
    branches: [ stable ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git fetch --prune --depth=1 --force --verbose origin
            git checkout --force origin/`echo '${{ github.ref }}' | sed 's/.*\///'`
            bash ./deploy.sh
